# Generated by Django 6.0.3 on 2026-04-21 08:19

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('super_mart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_display',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
