# Generated by Django 6.0.3 on 2026-04-16 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_mart', '0002_alter_product_category_alter_product_main_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_path',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('food', 'Food & Drinks'), ('electronics', 'Electronics'), ('office', 'Office Supplies'), ('style&fashion', 'Style & Fashion'), ('home', 'Home & Garden'), ('toys', 'Toys & Games '), ('health', 'Health & Beauty'), ('sports', 'Sports & Outdoors'), ('automotive', 'Automotive'), ('books', 'Books & Media'), ('miscKitchen', 'Kitchen & Dining'), ('sex-toys', 'Sex-Toys'), ('rent-house', 'House-Rent'), ('car-sales', 'Car-Sales'), ('kitchen-items', 'Kitchen-Items')], max_length=100),
        ),
    ]
