# Generated by Django 6.0.3 on 2026-04-21 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_mart', '0003_profile_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='gross_salary',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
