# Generated by Django 6.0.3 on 2026-04-24 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_mart', '0004_alter_payroll_amount_alter_payroll_gross_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(db_column='department_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='super_mart.department'),
        ),
    ]
