# Generated by Django 6.0.3 on 2026-04-13 10:09

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_mart', '0017_product_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('link_url', models.URLField(blank=True, help_text='Where the user goes when they click', null=True)),
                ('location', models.CharField(choices=[('header_main', 'Top Header (Near Logo)'), ('sidebar', 'Sidebar'), ('popup', 'Flash Sale Popup')], default='header_main', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
