# Generated by Django 6.0.3 on 2026-04-13 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('super_mart', '0018_advertisement_alter_productimage_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertisement',
            old_name='name',
            new_name='title',
        ),
    ]
