# Generated by Django 6.0.3 on 2026-04-13 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_mart', '0019_rename_name_advertisement_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Advertisement',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/gallery/'),
        ),
    ]
