# Generated by Django 6.0.3 on 2026-04-13 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_mart', '0021_advertisement_remove_product_image_path_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Advertisement',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.AddField(
            model_name='product',
            name='image_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('food', 'Food & Drinks'), ('electronics', 'Electronics'), ('office', 'Office Supplies'), ('style&fashion', 'Style & Fashion'), ('home', 'Home & Garden'), ('toys', 'Toys & Games '), ('health', 'Health & Beauty'), ('sports', 'Sports & Outdoors'), ('automotive', 'Automotive'), ('books', 'Books & Media'), ('miscKitchen', 'Kitchen & Dining'), ('sex-toys', 'Sex-Toys'), ('rent-house', 'House-Rent'), ('car-sales', 'Car-Sales'), ('kitchen-items', 'Kitchen-Items')], max_length=50),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/gallery/'),
        ),
    ]
