# Generated by Django 6.0.3 on 2026-04-13 20:35

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_mart', '0022_delete_advertisement_remove_product_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_path',
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('food', 'Food & Drinks'), ('electronics', 'Electronics'), ('office', 'Office Supplies'), ('style&fashion', 'Style & Fashion'), ('sex-toys', 'Sex-Toys'), ('rent-house', 'House-Rent'), ('car-sales', 'Car-Sales'), ('kitchen-items', 'Kitchen-Items')], max_length=50),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
