server {
    listen 10000;
    server_name localhost;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # API Proxies
    location /api/invoices/ {
        proxy_pass https://invoice-service-ttn6.onrender.com/api/invoices/;
        proxy_set_header Host invoice-service-ttn6.onrender.com;
    }

    location /api/employees/ {
        proxy_pass https://employee-management-app-wuq1.onrender.com/api/employees/;
        proxy_set_header Host employee-management-app-wuq1.onrender.com;
    }

    location /api/ {
        proxy_pass https://back-end-wdk7.onrender.com/api/;
        proxy_set_header Host back-end-wdk7.onrender.com;
    }
}